IS_3_14=YES
MAKEFOR=SCILAB

ifeq ($(IS_3_14),YES)
EPICS_TOP = /afs/slac/g/spear/epics/base
EPICS_BASE = $(EPICS_TOP)//
EPICS_EXTENSIONS = .
HARCH = $(EPICS_HOST_ARCH)
TARCH = Linux
else
EPICS_TOP = /home/till_tp/till/epics/R3.13.6
EPICS_BASE = $(EPICS_TOP)/base-3.13.6/
EPICS_EXTENSIONS = /afs/slac/g/spear/epics/extensions
HARCH = Linux
TARCH = Linux
endif

ifeq ($(MAKEFOR),MATLAB)
SCIINC = /afs/slac/package/matlab/linux/14B2/extern/include/
MAKEFORDEF = -DMATLAB_APP
TARGETS = libmezcaglue.so
else
SCIDIR = /usr/lib/scilab-2.7
SCIINC = $(SCIDIR)/routines
TARGETS = ezca.o ecget.o ezcaWrap.o
MAKEFORDEF = -DSCILAB_APP
endif


ifeq ($(IS_3_14),YES)
PTHREAD = -lpthread
LIBS = -L$(EPICS_BASE)/lib/$(HARCH)/ -lca -lCom -lrt
#-lreadline -ltermcap -lrt
else
LIBS = -L$(EPICS_BASE)/lib/$(HARCH)/ -lca -lCom -L/lib -L/usr/lib -lm -lrt
endif
INCS = -I$(EPICS_BASE)/include/ -I$(EPICS_BASE)/include/os/$(TARCH)
EINCS = -I$(EPICS_EXTENSIONS)/include/
ELIBS = -L$(EPICS_EXTENSIONS)/lib/$(HARCH)/ -lezca

INTERSCI = $(SCIDIR)/bin/intersci

all: ecget multiEzca.o $(TARGETS)

ezca.o: ezca.tmp.f
	$(FC) -c $(FFLAGS) -o $@ $<

%.tmp.f: %.f
	$(RM) -f $@
	sed -e 's|SCIDIR|$(SCIDIR)|g' $^ > $@

%.f:	%.desc
	$(SCIDIR)/bin/intersci $(<:%.desc=%)
	
caget: caget.c
	$(CC) -o $@ $(CFLAGS) -fPIC $(INCS) $(EINCS) -I$(SCIINC) $< $(ELIBS) $(LIBS)

ecget.o: ecget.c
	$(CC) -c $(CFLAGS) -fPIC $(MAKEFORDEF) $(INCS) $(EINCS) -I$(SCIINC) $<

multiEzca.o: multiEzca.c multiEzca.h
	$(CC) -c $(CFLAGS) -fPIC $(MAKEFORDEF) $(INCS) $(EINCS) -I$(SCIINC) $<

ezcaWrap.o: ezcaWrap.c multiEzca.h
	$(CC) -c $(CFLAGS) -fPIC $(INCS) $(EINCS) -I$(SCIINC) $<

mglue.o: mglue.c mglue.h
	$(CC) -c $(CFLAGS) -fPIC $(INCS) $(MAKEFORDEF) $(EINCS) -I$(SCIINC) $<

#ezcaWrap.occ: ezcaWrap.cc
#	$(CXX) -c -o $@ $(CFLAGS) -fPIC $(INCS) $(EINCS) -I$(SCIINC) $<

#	$(CC) -Wl,"-Ur,-u ezcaGet" -o $@ $^ $(INCS) $(EINCS) -I$(SCIINC) -L$(EPICS_BASE)/lib/$(HARCH)/ $(ELIBS) -lca -lCom -L/lib -L/usr/lib/

libmezcaglue.so:  multiEzca.o mglue.o
	$(CXX) -shared -o $@ -fPIC $^ -Lezca/lib/$(HARCH) -L$(EPICS_BASE)/lib/$(HARCH) -Wl,-rpath,ezca/lib/$(HARCH) -Wl,-rpath,$(EPICS_BASE)/lib/$(HARCH) -lezca314 -lca -lCom  -lm
#	$(LD) -i -o $@ $^ -L/usr/lib $(ELIBS) $(EPICS_BASE)/lib/$(HARCH)/libca.a $(EPICS_BASE)/lib/$(HARCH)/libCom.a

ecget: ecget.c
#	$(CC) -O2 -o $@ $^ $(INCS) $(LIBS)
	$(CC) $(CFLAGS) -o $@ $^ -DCMDLINE_APP $(INCS) $(LIBS) $(PTHREAD)

caInf: caInf.c
	$(CC) -O2 -o $@ $^ $(EINCS) $(INCS) $(ELIBS) $(LIBS) $(PTHREAD)

clean:
	$(RM) libmezcaglue.so *.o ezca.f ecget caInf ezca.tmp.f ezca.sce *.mex???
