IS_3_14=YES
ifeq ($(IS_3_14),YES)
EPICS_TOP = /afs/slac/g/spear/epics/base
EPICS_BASE = $(EPICS_TOP)//
EPICS_EXTENSIONS = .
HARCH = $(EPICS_HOST_ARCH)
TARCH = Linux
else
EPICS_TOP = /home/till_tp/till/epics/R3.13.6
EPICS_BASE = $(EPICS_TOP)/base-3.13.6/
EPICS_EXTENSIONS = /afs/slac/g/spear/epics/extensions
HARCH = Linux
TARCH = Linux
endif
SCIDIR = /usr/lib/scilab-2.7

ifeq ($(IS_3_14),YES)
PTHREAD = -lpthread
LIBS = -L$(EPICS_BASE)/lib/$(HARCH)/ -lca -lCom -lrt
#-lreadline -ltermcap -lrt
else
LIBS = -L$(EPICS_BASE)/lib/$(HARCH)/ -lca -lCom -L/lib -L/usr/lib -lm -lrt
endif
INCS = -I$(EPICS_BASE)/include/ -I$(EPICS_BASE)/include/os/$(TARCH)
EINCS = -I$(EPICS_EXTENSIONS)/include/
ELIBS = -L$(EPICS_EXTENSIONS)/lib/$(HARCH)/ -lezca

INTERSCI = $(SCIDIR)/bin/intersci

all: ezca.o ecget ecget.o ezcaWrap.o

ezca.o: ezca.tmp.f
	$(FC) -c $(FFLAGS) -o $@ $<

%.tmp.f: %.f
	$(RM) -f $@
	sed -e 's|SCIDIR|$(SCIDIR)|g' $^ > $@

%.f:	%.desc
	$(SCIDIR)/bin/intersci $(<:%.desc=%)
	
caget: caget.c
	$(CC) -o $@ $(CFLAGS) -fPIC -DSCILAB_APP $(INCS) $(EINCS) -I$(SCIDIR) $< $(ELIBS) $(LIBS)

ecget.o: ecget.c
	$(CC) -c $(CFLAGS) -fPIC -DSCILAB_APP $(INCS) $(EINCS) -I$(SCIDIR) $<

ezcaWrap.o: ezcaWrap.c
	$(CC) -c $(CFLAGS) -fPIC $(INCS) $(EINCS) -I$(SCIDIR)/routines $<

ezcaWrap.occ: ezcaWrap.cc
	$(CXX) -c -o $@ $(CFLAGS) -fPIC $(INCS) $(EINCS) -I$(SCIDIR) $<

#	$(CC) -Wl,"-Ur,-u ezcaGet" -o $@ $^ $(INCS) $(EINCS) -I$(SCIDIR) -L$(EPICS_BASE)/lib/$(HARCH)/ $(ELIBS) -lca -lCom -L/lib -L/usr/lib/
ezcalib:  ezcaWrap.o ecget.o
#	$(CXX) -r -o $@ -fPIC $^ $(EPICS_EXTENSIONS)/lib/$(HARCH)/libezca.a -L/lib -L/usr/lib -lm
	$(LD) -i -o $@ $^ -L/usr/lib $(ELIBS) $(EPICS_BASE)/lib/$(HARCH)/libca.a $(EPICS_BASE)/lib/$(HARCH)/libCom.a

ecget: ecget.c
#	$(CC) -O2 -o $@ $^ $(INCS) $(LIBS)
	$(CC) $(CFLAGS) -o $@ $^ -DCMDLINE_APP $(INCS) $(LIBS) $(PTHREAD)

caInf: caInf.c
	$(CC) -O2 -o $@ $^ $(EINCS) $(INCS) $(ELIBS) $(LIBS) $(PTHREAD)

clean:
	$(RM) ezcalib *.o ezca.f ecget caInf ezca.tmp.f ezca.sce
