mex ecget.c Q:\Groups\Accel\Controls\EPICS\R3.13.4\base\lib\Win32\Com.lib...
    Q:\Groups\Accel\Controls\EPICS\R3.13.4\base\lib\Win32\ca.lib -DDB_TEXT_GLBLSOURCE ...
    -D_WIN32 -DEPICS_DLL_NO -DMATLAB_APP ...     
    -IQ:\Groups\Accel\Controls\EPICS\R3.13.4\base\include...
    -IQ:\Groups\Accel\Controls\EPICS\R3.13.4\base\include\os\WIN32 ...
    -v

