function mkmezca()
%mk('ecget.c')
%mk('ezcaGetControlLimits.c')
%mk('ezcaPut.c')
%mk('ezcaGet.c')
mk('ezcaGetNelem.c')
%
%
function mk(feil)
eval(['mex -v -g -DMATLAB_APP -I. -I./include',...
' -IM:/g/spear/3.14.2epics/base/include',...
' -IM:/g/spear/3.14.2epics/base/include/os/WIN32 ',...
feil,...
' lib/win32-x86/mezcaglue.lib',...
' lib/win32-x86/ezca.lib',...
' M:/g/spear/3.14.2epics/base/lib/win32-x86/ca.lib',...
' M:/g/spear/3.14.2epics/base/lib/win32-x86/Com.lib'])
%-L/afs/slac/g/spear/epics/base/lib/linux-x86 -Llib/linux-x86 -lezca314 -lca -lCom
